### ISSUE TITLE
Unknown symbol "Work" (char 0) error on a high amount of concurrent executions

### ISSUE THREAD

**Issue by sambP** [DeFiCh/jellyfishsdk#1662]
Hi, I'm running into a strange error when executing a large number of concurrent RPC calls. If I do the same sequentially, all works fine. My current workaround is a middleware, which secures that at most 20 calls running at a time, but this seems a little bit hacky to me. 

```js
import { JsonRpcClient } from '@defichain/jellyfish-api-jsonrpc';

(async function start() {
  const rpcClient = new JsonRpcClient('url');
  const calls = new Array(500).fill(0);

  // does work
  // for (const call of calls) await rpcClient.blockchain.getBlockCount();

  // produces error
  await Promise.all(calls.map(() => rpcClient.blockchain.getBlockCount()));

  process.exit();
})();
```

```
(node:15761) UnhandledPromiseRejectionWarning: SyntaxError: Unknown symbol "Work" (char 0)
    at SyntaxError.<anonymous> (/Users/sambp/software/chainreport-web/node_modules/core-js/internals/wrap-error-constructor-with-cause.js:37:62)
    at new SyntaxError (/Users/sambp/software/chainreport-web/node_modules/core-js/modules/es.error.cause.js:40:49)
    at createSyntaxError (/Users/sambp/software/chainreport-web/node_modules/lossless-json/lib/parse.js:300:15)
    at parseSymbol (/Users/sambp/software/chainreport-web/node_modules/lossless-json/lib/parse.js:466:11)
    at parseNumber (/Users/sambp/software/chainreport-web/node_modules/lossless-json/lib/parse.js:444:10)
    at parseString (/Users/sambp/software/chainreport-web/node_modules/lossless-json/lib/parse.js:430:10)
    at parseArray (/Users/sambp/software/chainreport-web/node_modules/lossless-json/lib/parse.js:416:10)
    at parseObject (/Users/sambp/software/chainreport-web/node_modules/lossless-json/lib/parse.js:369:10)
    at Object.r.parse (/Users/sambp/software/chainreport-web/node_modules/lossless-json/lib/parse.js:85:14)
    at Object.parse (/Users/sambp/software/chainreport-web/node_modules/@defichain/jellyfish-json/src/index.ts:62:25)
```

**Comment by fuxingloh** [comment]
Seems like you have a middleware or proxy between services? The jellyfish client failed to parse that response, I believe `defid` is rejecting those requests due to RPC work queue limit. Hence I assume the "Work" symbol error.

You can change the RPC work queue by doing this:

https://github.com/JellyfishSDK/jellyfish/blob/7e88ff530a4f97216086c6e09ec23654c7778033/apps/whale-api/docker-compose.yml#L15

**Comment by sambP** [comment]
Yes, there is a proxy and a load balancer in between. I was unable to reproduce this error after I added this option. So it seems to work. Thanks a lot!
